server:
  port: 8081
spring:
  application:
    name: 1118-service
eureka:
  client:
    # 注册中心服务地址，你要向哪个注册中心注册
    service-url:
      defaultZone: http://localhost:10001/eureka/
    #当前应用是否注册到Eureka注册中心（默认就是true，因此无需配置）
    #    register-with-eureka: true
    #是否向Eureka注册中心拉取服务列表（默认就是true，因此无需配置）
    #    fetch-registry: true
bp:
  info: 8081

